### ISSUE TITLE
Add FireEye blog covering IronGate

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#10]
Release date: (06/02/2016)

Vendor: FireEye

Link: https://www.fireeye.com/blog/threat-research/2016/06/irongate_ics_malware.html

PDF:

Group:

Other: Irongate, ICS

**Comment by kbandla** [comment]
`FireEye_IRONGATE_ICS(06-02-2016).pdf` added to box

**Comment by beast-fighter** [comment]
added in 5cc516e
