### ISSUE TITLE
Dissecting the APT28 Mac OS X Payload

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#105]
Please fill out the information below

Release date: (02/23/2017)

Vendor: BitDefender

Link: https://download.bitdefender.com/resources/files/News/CaseStudies/study/143/Bitdefender-Whitepaper-APT-Mac-A4-en-EN-web.pdf

PDF: https://download.bitdefender.com/resources/files/News/CaseStudies/study/143/Bitdefender-Whitepaper-APT-Mac-A4-en-EN-web.pdf

Group: APT28

Other:

**Comment by kbandla** [comment]
```
{'Date': '02/23/2017',
 'Filename': u'Bitdefender-Whitepaper-APT-Mac-A4-en-EN-web(02-23-2017).pdf',
 'Pdf': u'https://app.box.com/s/l7n781ig6n8wlf1aff5hgwbh4qoi5jqq',
 'SHA-1': 'd206b485a42c611ed9fe6a0b1a3ed086e954bd30',
 'Source': 'Bitdefender',
 'Title': 'Dissecting the APT28 Mac OS X Payload',
 'Year': '2017'}
```
