### ISSUE TITLE
Spear Phishing Techniques Used in Attacks Targeting the Mongolian Government

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#106]
Please fill out the information below

Release date: (02/22/2017)

Vendor: FireEye

Link: https://www.fireeye.com/blog/threat-research/2017/02/spear_phishing_techn.html

PDF:
[Spear Phishing Techniques Used in Attacks Targeting the Mongolian Government - FireEye.pdf](https://github.com/aptnotes/data/files/796189/Spear.Phishing.Techniques.Used.in.Attacks.Targeting.the.Mongolian.Government.-.FireEye.pdf)
Group:

Other:

**Comment by kbandla** [comment]
```
{'Date': '02/22/2017',
 'Filename': u'Fireeye_SpearPhishing-Targeting-Mongolian-Government(02-22-2017).pdf',
 'Pdf': u'https://app.box.com/s/sgzri8xt5l6gaodokuvvfjt7emzu0z4o',
 'SHA-1': '7cb839427c1ed6c815f18b2677b905128b34e09c',
 'Source': 'FireEye',
 'Title': 'Spear Phishing Techniques Used in Attacks Targeting the Mongolian Government',
 'Year': '2017'}
```
thanks @threatminer !
