### ISSUE TITLE
ChChes – Malware that Communicates with C&C Servers Using Cookie Headers

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#107]
Please fill out the information below

Release date: (02/24/2017)

Vendor: JP-CERT

Link: http://blog.jpcert.or.jp/2017/02/chches-malware--93d6.html

PDF:
[JPCERT_CC Blog_ ChChes – Malware that Communicates with C&C Servers Using Cookie Headers.pdf](https://github.com/aptnotes/data/files/799170/JPCERT_CC.Blog_.ChChes.Malware.that.Communicates.with.C.C.Servers.Using.Cookie.Headers.pdf)

Group:

Other:

**Comment by kbandla** [comment]
```
{'Date': '02/17/2017',
 'Filename': u'JPCERT_ChChes-CampC-Cookie-Headers(02-17-2017).pdf',
 'Pdf': u'https://app.box.com/s/ud9z8kc33scu3fwbon1at9lcul9h9hw3',
 'SHA-1': 'eeba6bed9a01db3c222e37438c5ea519eee7d617',
 'Source': 'JPCERT',
 'Title': 'ChChes - Malware that Communicates with C&C Servers Using Cookie Headers',
 'Year': '2017'}
```
