### ISSUE TITLE
The Deception Project: A New Japanese-Centric Threat

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#119]
Please fill out the information below

Release date: (02/27/2017)

Vendor: Cylance

Link:  https://www.cylance.com/en_us/blog/the-deception-project-a-new-japanese-centric-threat.html

PDF:
[The Deception Project A New Japanese-Centric Threat - Cylance.pdf](https://github.com/aptnotes/data/files/841099/The.Deception.Project.A.New.Japanese-Centric.Threat.-.Cylance.pdf)

Group:

Other:

**Comment by kbandla** [comment]
```
{   'Date': '02/27/2017',
    'Filename': u'Cylance_DeceptionProject-New-Japanese-Centric-Threat(02-27-2017).pdf',
    'Pdf': u'https://app.box.com/s/5l02xyf45l1gww8vet75vom5jmn32m0h',
    'SHA-1': '0b30c4bd931d88806fcbd98cb740e5b111fc8f42',
    'Source': 'Cylance',
    'Title': 'The Deception Project: A New Japanese-Centric Threat',
    'Year': '2017'}
```
