### ISSUE TITLE
Add FireEye report: APT GROUP SENDS SPEAR PHISHING EMAILS TO INDIAN GOVERNMENT OFFICIALS

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#12]
Release date: (06/03/2016)

Vendor: FireEye

Link:  https://www.fireeye.com/blog/threat-research/2016/06/apt_group_sends_spea.html

PDF:

Group: suspected Pakistan-based APT group

Other: 
On May 18, 2016, FireEye Labs observed a suspected Pakistan-based APT group sending spear phishing emails to Indian government officials. This threat actor has been active for several years and conducting suspected intelligence collection operations against South Asian political and military targets.

**Comment by kbandla** [comment]
`FireEye_IndianGovSpearPhish(06-03-2016).pdf` added to box

**Comment by beast-fighter** [comment]
added in ff021fb
