### ISSUE TITLE
operation cloud hopper

### ISSUE THREAD

**Issue by KaptainKool** [aptnotes/data#125]
Please fill out the information below

Release date: (04/03/2017)

Vendor: PwC & BAE

Link: https://www.pwc.co.uk/issues/cyber-security-data-privacy/insights/operation-cloud-hopper.html

PDF:

Group:

Other:

**Comment by KaptainKool** [comment]
Related:

https://www.us-cert.gov/sites/default/files/publications/IR-ALERT-MED-17-093-01C-Intrusions_Affecting_Multiple_Victims_Across_Multiple_Sectors.pdf

**Comment by kbandla** [comment]
```
{   'Date': '04/03/2017',
    'Filename': u'PWC_cloud-hopper-report-final-v4(04-03-2017).pdf',
    'Pdf': u'https://app.box.com/s/ifeoa5huug0aqdecsniw7jmrxym0k85i',
    'SHA-1': '4082ecd0d6b73061fc12d099d0b1b257b3d6a71d',
    'Source': 'PWC',
    'Title': 'Operation Cloud Hopper',
    'Year': '2017'}
```
