### ISSUE TITLE
Add Trend Report: Looking Into a Cyber-Attack Facilitator in the Netherlands

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#13]
Release date: (04/21/2016)

Vendor: TrendMicro

Link: http://blog.trendmicro.com/trendlabs-security-intelligence/looking-into-a-cyber-attack-facilitator-in-the-netherlands/

PDF: (Appendix) http://documents.trendmicro.com/assets/appendix_looking-into-a-cyber-attack-facilitator-in-the-netherlands.pdf

Group:

Other:

**Comment by kbandla** [comment]
`TrendMicro_NetherlandsCyberAttack(04-21-2016).pdf` added to box

**Comment by beast-fighter** [comment]
added in b326873
