### ISSUE TITLE
Operation Cobalt Kitty Threat Actor Profile & Indicators of Compromise

### ISSUE THREAD

**Issue by tjgerot** [aptnotes/data#147]
Release date: (05/24/2017)

Vendor: Cybereason https://www.cybereason.com/

Link: https://www.cybereason.com/blog-cybereason-labs-discovery-operation-cobalt-kitty-a-large-scale-apt-in-asia-carried-out-by-the-oceanlotus-group/

PDF: https://www2.cybereason.com/asset/61:research-cobalt-kitty-profile-iocs

Group: APT32 OceanLotus

**Comment by kbandla** [comment]
Looks like we have added this report recently: 
https://app.box.com/s/0bfouh1vvqc8esyh7tdvw2ttpsqzu1kh

Did not add the IOC file. Did it now:
```
{ 'Date': '05/24/2017', 'Filename': u'Cybereason_Cobalt-Kitty-ActorsProfiles-IOCs(05-24-2017).pdf', 'Pdf': u'https://app.box.com/s/qmhs1k5awl5ibders0bwdlt9f9omhm4m', 
'SHA-1': '62bad1275ebdb062b9df708c1b71c34e5b92f310', 
'Source': 'Cybereason', 
'Title': 'Operation Cobalt Kitty Threat Actor Profile & IOC', 
'Year': '2017'}
```
