### ISSUE TITLE
The DarkHotel APT - A Story of Unusual Hospitality

### ISSUE THREAD

**Issue by tjgerot** [aptnotes/data#148]
**Release Date:** 11/10/2014

**Vendor:** Kaspersky Lab

**Link:** https://securelist.com/the-darkhotel-apt/66779/

**PDF:** https://securelist.com/files/2014/11/darkhotel_kl_07.11.pdf

**Group:** Darkhotel APT

<hr>

**Release Date:** 08/10/2015

**Vendor:** Kaspersky Lab

**Link:** https://securelist.com/the-darkhotel-apt/66779/

**PDF:** http://newsroom.kaspersky.eu/fileadmin/user_upload/fr/Campaign/Miscellaneous/Kaspersky_Report_Darkhotel_2015.pdf

**Group:** Darkhotel APT

**Comment by kbandla** [comment]
```
   'Date': '11/10/2014',
    'Filename': u'Kaspersky_Darkhotel_kl_07.11_1.1(11-10-2014).pdf',
    'Pdf': u'https://app.box.com/s/f6bmfscrmam0oq111f9u4bwiqu74bxyi',
    'SHA-1': 'fab8b6fddc50a533d5b537b27156cb265fea7f02',
    'Source': 'Kaspersky',
    'Title': 'The Darkhotel APT A Story of Unusual Hospitality v1.1',
    'Year': '2014'}
```

```
{   'Date': '08/10/2015',
    'Filename': u'Kaspersky_Report_Darkhotel_2015(08-10-2015).pdf',
    'Pdf': u'https://app.box.com/s/fu1lu7lza8h4znv76a5dqlrjubapxw92',
    'SHA-1': '034b5ef9a0a81222ce6fec74f19884af4d02353e',
    'Source': 'Kaspersky',
    'Title': 'Darkhotel's attacks in 2015 ',
    'Year': '2015'}```

**Comment by kbandla** [comment]
Nice find @tjgerot !
Added updated reports.
