### ISSUE TITLE
Strontium

### ISSUE THREAD

**Issue by kbandla** [aptnotes/data#15]
Please fill out the information below

Release date: (11/16/2015)

Vendor: Microsoft

Link: 

PDF: http://download.microsoft.com/download/4/4/C/44CDEF0E-7924-4787-A56A-16261691ACE3/Microsoft_Security_Intelligence_Report_Volume_19_English.pdf

Group: APT28

Other:

**Comment by kbandla** [comment]
`Microsoft_Security_Intelligence_Report_Volume_19_English(11-16-2015)` added to box/2015

**Comment by beast-fighter** [comment]
added in 70628e3
