### ISSUE TITLE
[SecureWorks] BRONZE BUTLER

### ISSUE THREAD

**Issue by kbandla** [aptnotes/data#150]
Please fill out the information below

Release date: (mm/dd/2017)

Vendor: SecureWorks

Link: 

PDF: https://www.secureworks.jp/~/media/Files/JP/Reports/SecureWorksBronzeButlerReport.ashx

Group: 

Other:

**Comment by kbandla** [comment]
This is a .jp report. Should this be added?

**Comment by beast-fighter** [comment]
Yes, let's add for posterity sake

**Comment by kbandla** [comment]
```
{'Date': '06/23/2017',
 'Filename': u'Secureworks_Bronze-Butler-Report(06-23-2017).pdf',
 'Pdf': u'https://app.box.com/s/fz7ranw75zxuh6mc1023igycp1x96fs4',
 'SHA-1': 'e8e651ded2d19cb62556e14a2e79eec1e897c55d',
 'Source': 'Dell Secureworks',
 'Title': 'Bronze Butler',
 'Year': '2017'}
```
