### ISSUE TITLE
Operation Wilted Tulip – Exposing a Cyber Espionage Apparatus

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#153]
Release date: (07/25/2017)

Vendor: Clearsky, TrendMicro

Link: http://www.clearskysec.com/tulip/

PDF: http://www.clearskysec.com/wp-content/uploads/2017/07/Operation_Wilted_Tulip.pdf

Group: CopyKittens

Other:
http://www.clearskysec.com/wp-content/uploads/2017/07/indicators-wilted_tulip.csv (IOC)
http://www.clearskysec.com/wp-content/uploads/2017/07/yara-apt_wilted_tulip.txt (Yara)

**Comment by kbandla** [comment]
```
{   'Date': '07/25/2017',
    'Filename': u'Clearsky_Operation_Wilted_Tulip(07-25-2017).pdf',
    'Pdf': u'https://app.box.com/s/s0c9085u0otvi6slu121mqikt5h5dzvn',
    'SHA-1': '71cb0af91eb32f444cd97f40934b0337e03fd379',
    'Source': 'Clearsky',
    'Title': 'Operation Wilted Tulip',
    'Year': '2017'}
```

**Comment by kbandla** [comment]
@beast-fighter :+1:
