### ISSUE TITLE
Russian Bank Offices Hit with Broad Phishing Wave

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#154]
Release date: (08/18/2017)

Vendor: RSA

Link: https://community.rsa.com/community/products/netwitness/blog/2017/08/17/russian-bank-offices-hit-with-broad-phishing-wave

PDF:

Group:

Other:

**Comment by kbandla** [comment]
```
{   'Date': '08/18/2017',
    'Filename': u'RSA_Russian-Bank-Offices-Phishing-Wave(08-18-2017).pdf',
    'Pdf': u'https://app.box.com/s/xgtoqdnl8tdviws0jgvxnj8oniia4qqr',
    'SHA-1': 'c42879e3e3393f1cd6a716273d4eee1b023029bd',
    'Source': 'RSA',
    'Title': 'Russian Bank Offices Hit with Broad Phishing Wave',
    'Year': '2017'}
```

**Comment by CyberMonitor** [comment]
LINK change to  https://community.rsa.com/community/products/netwitness/blog/2017/08/18/russian-bank-offices-hit-with-broad-phishing-wave
