### ISSUE TITLE
Dragonfly 2.0. report

### ISSUE THREAD

**Issue by alessiodos** [aptnotes/data#158]
Release date: (06/09/2017)
Vendor: Symantec
Link: https://www.symantec.com/connect/blogs/dragonfly-western-energy-sector-targeted-sophisticated-attack-group
PDF:
[Dragonfly_ Western energy sector targeted by sophisticated attack group _ Symantec Connect Community.pdf](https://github.com/aptnotes/data/files/1281881/Dragonfly_.Western.energy.sector.targeted.by.sophisticated.attack.group._.Symantec.Connect.Community.pdf)
Group: 
Other:

**Comment by kbandla** [comment]
```
{   'Date': '09/06/2017',
    'Filename': u'Symantec_Dragonfly-Western-energy-sector-targeted(09-06-2017).pdf',
    'Pdf': u'https://app.box.com/s/4kpnzlrdqdcg3cq02hz4zj8nmjd9iywi',
    'SHA-1': 'c7d082f04cb0d613c04517d0d6dec2d76a866c6b',
    'Source': 'Symantec',
    'Title': 'Dragonfly: Western energy sector targeted by sophisticated attack group',
    'Year': '2017'}
```

**Comment by kbandla** [comment]
Thanks @alessiodos !
