### ISSUE TITLE
CrowdStrike's report on Cozy & Fancy bear

### ISSUE THREAD

**Issue by kbandla** [aptnotes/data#16]
Please fill out the information below

Release date: (06/14/2016)

Vendor: CrowdStrike

Link: https://www.crowdstrike.com/blog/bears-midst-intrusion-democratic-national-committee/

PDF:

Group: Cozy Bear & Fancy Bear

Other:

**Comment by kbandla** [comment]
`CrowdStrike-BearsintheMidst_DNC(06-04-2016).pdf` added to box

**Comment by beast-fighter** [comment]
added in 0f14ca7
