### ISSUE TITLE
[Sentryo] THREAT INTELLIGENCE REPORT CYBERATTACKS AGAINST UKRAINIAN ICS

### ISSUE THREAD

**Issue by alessiodos** [aptnotes/data#161]
Release date: (07/18/2017)

Vendor: sentryo

Link: https://www.sentryo.net/wp-content/uploads/2017/09/EBOOK_CYBERATTACKS-AGAINST-UKRAINIAN-ICS.pdf

PDF:  [20170612ac-ir_research_en (1).pdf](https://github.com/aptnotes/data/files/1352234/20170612ac-ir_research_en.1.pdf)

Group: 

Other:

**Comment by kbandla** [comment]
```
{'Date': '07/18/2017',
 'Filename': u'Sentryo_EBOOK_CYBERATTACKS-AGAINST-UKRAINIAN-ICS(07-18-2017).pdf',
 'Pdf': u'https://app.box.com/s/73gjx8wibk847zi2zq8cya9fj1ycqqxe',
 'SHA-1': '821e2036f0c3d06c508ad8c3442ef789d86d5bd6',
 'Source': 'Sentryo',
 'Title': 'Cyberattacks Against Ukrainian ICS',
 'Year': '2017'}
```
