### ISSUE TITLE
[Alien Vault] Newly Discovered Iranian APT Group Brings State-sponsored Cyber Espionage into Focus

### ISSUE THREAD

**Issue by bryanfreuler** [aptnotes/data#166]
Please fill out the information below

Release date: (10/17/2017)

Vendor: Alien Vault

Link: https://www.alienvault.com/blogs/security-essentials/newly-discovered-iranian-apt-group-brings-state-sponsored-cyber-espionage-into-focus

PDF:

Group: APT 33

Other:

**Comment by kbandla** [comment]
Hardly any information in the blog. Not going to add it.
