### ISSUE TITLE
Taiwan Heist: Lazarus Tools and Ransomware 

### ISSUE THREAD

**Issue by bryanfreuler** [aptnotes/data#167]
Release date: (10/16/2017)

Vendor: BAE Systems

Link: http://baesystemsai.blogspot.co.uk/2017/10/taiwan-heist-lazarus-tools.html

PDF:

Group: Lazarus 

Other:

**Comment by kbandla** [comment]
@bryanfreuler, looks like we added this in b6ee3f8e0807b3bbe8e917b04cae4b97cd3a5a5b. 
hmm maybe we should be saving the original url too, so that its possible to check...
