### ISSUE TITLE
Add Unit42 Sofacy blog 

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#17]
Release date: (06/14/2016)

Vendor: Palo Alto

Link:  
http://researchcenter.paloaltonetworks.com/2016/06/unit42-new-sofacy-attacks-against-us-government-agency/

PDF:

Group: APT28, Sofacy

Other:

**Comment by kbandla** [comment]
`PaloAlto_SofacyUSGov(06-14-2016).pdf` added to box
`61c759fab05cb341d84f825452ad17cbcfb23c31`

**Comment by beast-fighter** [comment]
added in 4d8876c
