### ISSUE TITLE
Mofang: A politically motivated information stealing adversary

### ISSUE THREAD

**Issue by ZackUSAF82** [aptnotes/data#18]
Please fill out the information below

Release date: 05/17/2016

Vendor: Fox It Security

Link: https://foxitsecurity.files.wordpress.com/2016/06/fox-it_mofang_threatreport_tlp-white.pdf

PDF: [fox-it_mofang_threatreport_tlp-white.pdf](https://github.com/aptnotes/data/files/320081/fox-it_mofang_threatreport_tlp-white.pdf)

Group: Mofang

Other:

**Comment by kbandla** [comment]
`Fox-IT-mofang_threatreport_tlp-white(05-17-2016).pdf` added to box
`ffa66796bd7c7f077c31285e6563ccb522b7e9b1`

**Comment by beast-fighter** [comment]
added in 0aed364
