### ISSUE TITLE
Threat Group-4127

### ISSUE THREAD

**Issue by kbandla** [aptnotes/data#19]
Please fill out the information below

Release date: (06/16/2016)

Vendor: Dell SecureWorks

Link: https://www.secureworks.com/research/threat-group-4127-targets-hillary-clinton-presidential-campaign

PDF:

Group: APT28

Other:

**Comment by kbandla** [comment]
`Secureworks-TG-4127Clinton(06-16-2016).pdf` added to box

**Comment by beast-fighter** [comment]
Added in 363a905
