### ISSUE TITLE
[RSA] Inside the Response of a Unique CARBANAK Intrusion

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#190]
Please fill out the information below

Release date: (11/30/2017)

Vendor: RSA

Link: https://www.rsa.com/en-us/resources/inside-the-response-of-a-unique-carbanak-intrusion-white-paper

PDF: https://www.rsa.com/content/dam/en/white-paper/the-shadows-of-ghosts-carbanak-report.pdf

Group:

Other:

**Comment by kbandla** [comment]
```
{'Date': '11/30/2017',
 'Filename': u'RSA_the-shadows-of-ghosts-carbanak-report(11-30-2017).pdf',
 'Pdf': u'https://app.box.com/s/egwg3so00e433s191jow7xlb1o27z7m7',
 'SHA-1': '06c63b54de2848bff9557bc9c49bf75906273fb2',
 'Source': 'RSA',
 'Title': 'Inside the Response of a Unique CARBANAK Intrusion',
 'Year': '2017'}
```
