### ISSUE TITLE
[Proofpoint] North Korea Bitten by  Bitcoin Bug

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#193]
Please fill out the information below

Release date: (12/19/2017)

Vendor: Proofpoint

Link: https://www.proofpoint.com/us/threat-insight/post/north-korea-bitten-bitcoin-bug-financially-motivated-campaigns-reveal-new

PDF: https://www.proofpoint.com/sites/default/files/pfpt-us-wp-north-korea-bitten-by-bitcoin-bug.pdf

Group: Lazarus

Other:

**Comment by kbandla** [comment]
```
{'Date': '12/19/2017',
 'Filename': u'ProofPoint_us-wp-north-korea-bitten-by-bitcoin-bug(12-19-2017).pdf',
 'Pdf': u'https://app.box.com/s/xez1hl78xz2l55mqe5cqvlwb5ytckhxf',
 'SHA-1': 'd8ba9a371c7dc7e6608b92e8a671b82191d6c67a',
 'Source': 'Proofpoint',
 'Title': 'North Korea Bitten by Bitcoin Bug',
 'Year': '2017'}
```
