### ISSUE TITLE
Operation Daybreak

### ISSUE THREAD

**Issue by kbandla** [aptnotes/data#20]
Please fill out the information below

Release date: (06/17/2016)

Vendor: Kaspersky

Link: https://securelist.com/blog/research/75100/operation-daybreak/

PDF:

Group: ScarCruft

Other:

**Comment by kbandla** [comment]
`Kaspersky_ScarCruft-OpDaybreak(06-17-2016).pdf` added to box
`fb7781a1552ee8fcddd13fc560aa1dea9ad4955a`

**Comment by beast-fighter** [comment]
added in e154504
