### ISSUE TITLE
Missing download URL for Lookout_Dark-Caracal_srr_20180118_us_v.1.0(01-18-2018)

### ISSUE THREAD

**Issue by Taskr** [aptnotes/data#204]
Lookout_Dark-Caracal_srr_20180118_us_v.1.0(01-18-2018) entry added via commit b9bd66d does not list a download URL (It is instead listed as just True).

**Comment by vegarasmul** [comment]
This is still an issue even though the above issue#1 has been closed:
 {"SHA-1": "d5c605fd42adb5312d17a54d246d8178a6a9094c"
 "Title": "Dark Caracal Cyber-espionage at a Global Scale"
 "Filename": "Lookout_Dark-Caracal_srr_20180118_us_v.1.0(01-18-2018)"
 "Source": "Lookout"
 "Link": "True"
 "Year": "2018"
 "Date": "01/18/2018"}
