### ISSUE TITLE
[Intezer] Lazarus Group Targets More Cryptocurrency Exchanges and FinTech Companies

### ISSUE THREAD

**Issue by kbandla** [aptnotes/data#205]
Please fill out the information below

Release date: (mm/dd/yyyy) 03/28/2018

Vendor: Intezer

Link: http://www.intezer.com/lazarus-group-targets-more-cryptocurrency-exchanges-and-fintech-companies/

PDF:

Group:

Other:

**Comment by SwitHak** [comment]
PDF: Not available

Group: Lazarus (Campaign: Blockbuster)

Other: Targeted Phishing -> Malicious VBA -> RAT

**Comment by kbandla** [comment]
```
{'Date': '03/28/2018',
 'Filename': u'Intezer_Lazarus-Cryptocurrency-Exchanges-FinTech-Companies(03-28-2018).pdf',
 'Pdf': u'https://app.box.com/s/yepeditzh0t0upifbucv99utoretbbzl',
 'SHA-1': '97c1a7625602d1dc66a153016ac63631f9b65d82',
 'Source': 'Intezer',
 'Title': 'Lazarus Group Targets More Cryptocurrency Exchanges and FinTech Companies',
 'Year': '2018'}
```
