### ISSUE TITLE
Two Birds, One STONE PANDA

### ISSUE THREAD

**Issue by ghost** [aptnotes/data#216]
Release date: (08/30/2018)

Vendor: Crowdstrike

Link: https://www.crowdstrike.com/blog/two-birds-one-stone-panda/

PDF:

Group: STONE PANDA,  APT10

Other:

**Comment by kbandla** [comment]
Key | Value
---|---
Title | Two Birds, One STONE PANDA 
Source | Crowdstrike 
Date | 08/30/2018 
Year | 2018 
Filename | Crowdstrike_Two-Birds-One-STONEPANDA(08-30-2018).pdf 
SHA-1 | 6ae6923748844d1fbb0a08d07d6bcb1112122796 
Pdf | https://app.box.com/s/uupum93o78ta8zw7fsl8fv3nyzlpsvpi
