### ISSUE TITLE
Domestic Kitten: An Iranian Surveillance Operation

### ISSUE THREAD

**Issue by ghost** [aptnotes/data#217]
Release date: (09/07/2018)

Vendor: Checkpoint

Link: https://research.checkpoint.com/domestic-kitten-an-iranian-surveillance-operation/

PDF:

Group: Domestic Kitten

Other:

**Comment by kbandla** [comment]
Key | Value
---|---
Title | Domestic Kitten: An Iranian Surveillance Operation 
Source | Checkpoint 
Date | 09/07/2018 
Year | 2018 
Filename | Checkpoint_Domestic-Kitten-Iranian-Surveillance-Operation(09-07-2018).pdf 
SHA-1 | 60ffe642ed8d9d2171b4c44729c4687fe493e87d 
Pdf | https://app.box.com/s/48z6mq7k6xlzicxbj9360eskrta92fbm
