### ISSUE TITLE
[FireEye][APT41]-APT41: A Dual Espionage and Cyber Crime Operation

### ISSUE THREAD

**Issue by SwitHak** [aptnotes/data#223]
Report Name: APT41: A Dual Espionage and Cyber Crime Operation

Release date: 08/07/2019

Vendor: FireEye

Link: https://www.fireeye.com/blog/threat-research/2019/08/apt41-dual-espionage-and-cyber-crime-operation.html

PDF: https://content.fireeye.com/apt-41/rpt-apt41

Group: APT41

Other:

**Comment by kbandla** [comment]
Key | Value
---|---
Title | APT41: A Dual Espionage and Cyber Crime Operation 
Source | FireEye 
Date | 08/07/2019 
Year | 2019 
Filename | Fireeye_rpt-apt41(08-07-2019).pdf 
SHA-1 | 30de1a1401504cd9f028862b821b98348b53e676 
Pdf | https://app.box.com/s/tijt08320isuaywxn1swd2uvbus7v7zl

**Comment by kbandla** [comment]
Key | Value
---|---
Title | APT41: A Dual Espionage and Cyber Crime Operation 
Source | FireEye 
Date | 08/07/2019 
Year | 2019 
Filename | Fireeye_APT41-Dual-Espionage-Cyber-Crime-WebPage(08-07-2019).pdf 
SHA-1 | 251adf184f43ba9101a4f3df9ff87da065eb58b3 
Pdf | True
