### ISSUE TITLE
[FireEye][APT41]-GAME OVER: Detecting and Stopping an APT41 Operation

### ISSUE THREAD

**Issue by SwitHak** [aptnotes/data#224]
Report Name: GAME OVER: Detecting and Stopping an APT41 Operation

Release date: 08/19/2019

Vendor:  FireEye

Link: https://www.fireeye.com/blog/threat-research/2019/08/game-over-detecting-and-stopping-an-apt41-operation.html

PDF: none

Group: APT41

Other:

**Comment by kbandla** [comment]
Key | Value
---|---
Title | GAME OVER: Detecting and Stopping an APT41 Operation 
Source | FireEye 
Date | 08/19/2019 
Year | 2019 
Filename | Fireeye_GAMEOVER-Detecting-Stopping-APT41-Operation(08-19-2019).pdf 
SHA-1 | 8093d518676b9c7a41b83927198e16c08b187dbb 
Pdf | https://app.box.com/s/tm7vgs6gp84kz44xee2oh8xdqesnnmn5
