### ISSUE TITLE
[FireEye][APT34]-Hard Pass: Declining APT34’s Invite to Join Their Professional Network

### ISSUE THREAD

**Issue by SwitHak** [aptnotes/data#225]
Report Name: Hard Pass: Declining APT34’s Invite to Join Their Professional Network

Release date: 07/18/2019

Vendor: FireEye

Link: https://www.fireeye.com/blog/threat-research/2019/07/hard-pass-declining-apt34-invite-to-join-their-professional-network.html

PDF: none

Group: APT34

Other:

**Comment by kbandla** [comment]
Key | Value
---|---
Title | Hard Pass: Declining APT34's Invite to Join Their Professional Network 
Source | FireEye 
Date | 07/18/2019 
Year | 2019 
Filename | Fireeye_APT34-Invite-Join-Professional-Network(07-18-2019).pdf 
SHA-1 | f937f0fe43db587ba38a755f06fa76bcd75d47c7 
Pdf | https://app.box.com/s/xrhqs26aajdbb92ivgoenotrdykup5uu
