### ISSUE TITLE
[FireEye][CARBANAK]-CARBANAK Week Part One: A Rare Occurrence

### ISSUE THREAD

**Issue by SwitHak** [aptnotes/data#226]
Report Name: CARBANAK Week Part One: A Rare Occurrence

Release date: 04/22/2019

Vendor:  FireEye

Link: https://www.fireeye.com/blog/threat-research/2019/04/carbanak-week-part-one-a-rare-occurrence.html

PDF: none

Group: Carbanak

Other:

**Comment by kbandla** [comment]
Key | Value
---|---
Title | CARBANAK Week Part One: A Rare Occurrence 
Source | FireEye 
Date | 04/22/2019 
Year | 2019 
Filename | Fireeye_CARBANAK-Week-1-Rare-Occurrence(04-22-2019).pdf 
SHA-1 | d0506df85bd5faf87a4a67e6affcde4ce9dda48f 
Pdf | https://app.box.com/s/l3dcqd6i8rnmxgi0ykd9zfmlwctcaq1g
