### ISSUE TITLE
[FireEye][CARBANAK]-CARBANAK Week Part Two: Continuing the CARBANAK Source Code Analysis

### ISSUE THREAD

**Issue by SwitHak** [aptnotes/data#227]
Report Name: CARBANAK Week Part Two: Continuing the CARBANAK Source Code Analysis

Release date: 04/23/2019

Vendor:  FireEye

Link: https://www.fireeye.com/blog/threat-research/2019/04/carbanak-week-part-two-continuing-source-code-analysis.html

PDF: none

Group: Carbanak

Other:

**Comment by kbandla** [comment]
Key | Value
---|---
Title | CARBANAK Week Part Two: Continuing the CARBANAK Source Code Analysis 
Source | FireEye 
Date | 04/23/2019 
Year | 2019 
Filename | Fireeye_CARBANAK-Week-2-CARBANAK-SourceCode-Analysis(04-23-2019).pdf 
SHA-1 | 9468ff9d1bc06b4c9f187e4ab55ae485750d6c5b 
Pdf | https://app.box.com/s/etrhh2gb4df9sybsieg3xs1j9mx6yw8s
