### ISSUE TITLE
[FireEye][CARBANAK]-CARBANAK Week Part Three: Behind the CARBANAK Backdoor

### ISSUE THREAD

**Issue by SwitHak** [aptnotes/data#228]
Report Name: CARBANAK Week Part Three: Behind the CARBANAK Backdoor

Release date: 04/24/2019

Vendor: FireEye

Link: https://www.fireeye.com/blog/threat-research/2019/04/carbanak-week-part-three-behind-the-backdoor.html

PDF: none

Group: Carbanak

Other:

**Comment by kbandla** [comment]
Key | Value
---|---
Title | CARBANAK Week Part Three: Behind the CARBANAK Backdoor 
Source | FireEye 
Date | 04/24/2019 
Year | 2019 
Filename | Fireeye_CARBANAK-Week-3-Behind-CARBANAK-Backdoor(04-24-2019).pdf 
SHA-1 | 98775eb539a512859a786f6292cc6f6db04916b2 
Pdf | https://app.box.com/s/rel5slouyleepdl3u7xilbmzsuk091n3
