### ISSUE TITLE
[FireEye][CARBANAK]-CARBANAK Week Part Four: The CARBANAK Desktop Video Player

### ISSUE THREAD

**Issue by SwitHak** [aptnotes/data#229]
Report Name: CARBANAK Week Part Four: The CARBANAK Desktop Video Player

Release date: 04/25/2019

Vendor: FireEye

Link: https://www.fireeye.com/blog/threat-research/2019/04/carbanak-week-part-four-desktop-video-player.html

PDF: none

Group: Carbanak

Other:

**Comment by kbandla** [comment]
```
{'Date': '04/25/2019',
 'Filename': 'Fireeye_CARBANAK-Week-4-CARBANAK-Desktop-Video-Player(04-25-2019).pdf',
 'Pdf': 'https://app.box.com/s/30mizln4f525yv482qqampa8vybjj764',
 'SHA-1': '7de0fbb852cc5be3fce91725a1b0aeb9abe3a43b',
 'Source': 'FireEye',
 'Title': 'CARBANAK Week Part Four: The CARBANAK Desktop Video Player',
 'Year': '2019'}
```

**Comment by kbandla** [comment]
Key | Value
---|---
Date | 04/25/2019 
Filename | Fireeye_CARBANAK-Week-4-CARBANAK-Desktop-Video-Player(04-25-2019).pdf 
Pdf | https://app.box.com/s/30mizln4f525yv482qqampa8vybjj764 
SHA-1 | 7de0fbb852cc5be3fce91725a1b0aeb9abe3a43b 
Source | FireEye 
Title | CARBANAK Week Part Four: The CARBANAK Desktop Video Player 
Year | 2019
