### ISSUE TITLE
PLATINUM

### ISSUE THREAD

**Issue by kbandla** [aptnotes/data#23]
Please fill out the information below

Release date: (04/26/2016)

Vendor: Microsoft

Link: https://blogs.technet.microsoft.com/mmpc/2016/04/26/digging-deep-for-platinum/

PDF: http://download.microsoft.com/download/2/2/5/225BFE3E-E1DE-4F5B-A77B-71200928D209/Platinum%20feature%20article%20-%20Targeted%20attacks%20in%20South%20and%20Southeast%20Asia%20April%202016.pdf

Group: ?

Other:

**Comment by beast-fighter** [comment]
This report was already added in May and is available here: https://app.box.com/s/ursk78m124t1lagjnu2862kumrnoshcp
