### ISSUE TITLE
Tracking Elirks Variants in Japan: Similarities to Previous Attacks

### ISSUE THREAD

**Issue by to4kawa** [aptnotes/data#25]
Please fill out the information below

Release date: (06/23/2016)

Vendor: Palo Alto

Link: http://researchcenter.paloaltonetworks.com/2016/06/unit42-tracking-elirks-variants-in-japan-similarities-to-previous-attacks/

PDF:

Group:Scarlet Mimic

Other:

**Comment by kbandla** [comment]
```
PaloAlto_TrackingElirksJapanSimilaritiesPreviousAttacks(06-23-2016).pdf
Tracking Elirks Variants in Japan: Similarities to Previous Attacks
Palo Alto
https://app.box.com/s/ki60vxvdi2wzqrsrqik0yvg4sdwsbbal
eba3ad81b20ed7b9ef081714928ecf1a4324b057
06/23/2016
2016
```

**Comment by kbandla** [comment]
Added in ce01dd1d750ca776996925d770dc531a533d6465
