### ISSUE TITLE
Add Unit42 Prince of Persia Game Over Blog

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#26]
Release date: (06/28/2016)

Vendor: Palo Alto (Unit 42)

Link: http://researchcenter.paloaltonetworks.com/2016/06/unit42-prince-of-persia-game-over/

PDF:

Group: Unknown

Other: Infy

**Comment by kbandla** [comment]
```
PaloAlto_PrinceofPersiaGameOver(06-28-2016).pdf
Prince of Persia Game Over
Palo Alto
https://app.box.com/s/drj4vb73cv87ok5wks21rynlq3236793
3f92bfbfdb0fee7eda8613fc3a6ff515ffceb972
06/28/2016
2016
```

**Comment by kbandla** [comment]
Added in ce01dd1d750ca776996925d770dc531a533d6465
