### ISSUE TITLE
Missing URL for Fireeye_APT41-Dual-Espionage-Cyber-Crime-WebPage(08-07-2019)

### ISSUE THREAD

**Issue by nikstur** [aptnotes/data#265]
In both the Json and the CSV the URL for the file "Fireeye_APT41-Dual-Espionage-Cyber-Crime-WebPage(08-07-2019)" is missing and instead replaced with the value "True".

In the Json:

```
{
  "Filename": "Fireeye_APT41-Dual-Espionage-Cyber-Crime-WebPage(08-07-2019)",
  "Title": "APT41: A Dual Espionage and Cyber Crime Operation",
  "Source": "FireEye",
  "Link": "True",
  "SHA-1": "251adf184f43ba9101a4f3df9ff87da065eb58b3",
  "Date": "08/07/2019",
  "Year": "2019"
}
```

And in the CSV on line 535:

`Fireeye_APT41-Dual-Espionage-Cyber-Crime-WebPage(08-07-2019),APT41: A Dual Espionage and Cyber Crime Operation,FireEye,True,251adf184f43ba9101a4f3df9ff87da065eb58b3,08/07/2019,2019`

**Comment by kbandla** [comment]
@nikstur thanks for pointing this, will fix this
