### ISSUE TITLE
SHA-1 hashes don't match what is listed, change everytime

### ISSUE THREAD

**Issue by aggiebill** [aptnotes/data#37]
I'm writing a script to download all of the pdfs for local viewing.  I noticed that all of the SHA-1 hashes of the downloaded files didn't match those in the csv and json files.

Sample:
```
PaloAlto_PrinceofPersiaGameOver(06-28-2016).pdf
Reported SHA-1:   3f92bfbfdb0fee7eda8613fc3a6ff515ffceb972
Calculated SHA-1: 88c16ea6054c620b3d322e74b9a565570ba9ec89
Bitdefender_Pacifier-APT(7-1-2016).pdf
Reported SHA-1:   6289dff2cbd2750c76517007989483922179fa40
Calculated SHA-1: 7092c099c42701a17292c0fbcc4573a5f302975c
Cymmetria_Unveiling-Patchwork(Jul-7-16).pdf
Reported SHA-1:   955ddb4453827e2c1664f2924e75b21fb0c0496d
Calculated SHA-1: 557a6c573ea2b6f89d7ebe3d4947ec2672ae757e
ESET_targeting-Central-and-EasternEurope(07-01-2016).pdf
Reported SHA-1:   8d9af4bb8b4bafcb9e58ab21e1419abd2eed46b2
Calculated SHA-1: 1cb7178f8cbb5733e30d9301e4be3e1efcb9d2dd
JPCERT_AsruexShortcutFiles(06-30-2016).pdf
Reported SHA-1:   0ddd9b23aaa773615e7d6392969d40b332e0c85f
Calculated SHA-1: 7b312a852aaa0156d09d61dd0bc0212ff3d30420
Proofpoint_NetTraveler-TargetsRussianEuropean(07-07-2016).pdf
Reported SHA-1:   d647ecd9a694447bc8ee9096f425ba29d93f7fb7
Calculated SHA-1: d95b55d084c7bf68d7a6dcc3275a56a01753f135
Kaspersky_DroppingElephant(07-08-2016).pdf
Reported SHA-1:   e0606a9e6a785d942b50d281d87550dc03d3666e
Calculated SHA-1: 354393d7471b6895e55373b3f96991267bd694c6
```

I deleted all of the files and ran the code again.  This time I got different /incorrect SHA-1 hashes.  

```
PaloAlto_PrinceofPersiaGameOver(06-28-2016).pdf
Reported SHA-1:   3f92bfbfdb0fee7eda8613fc3a6ff515ffceb972
Calculated SHA-1: b4518eb101c228e815ed6707eaa3988d3c9f731d
Bitdefender_Pacifier-APT(7-1-2016).pdf
Reported SHA-1:   6289dff2cbd2750c76517007989483922179fa40
Calculated SHA-1: 83e791a84ea77977e466514996fd3268c5ed8ba6
Cymmetria_Unveiling-Patchwork(Jul-7-16).pdf
Reported SHA-1:   955ddb4453827e2c1664f2924e75b21fb0c0496d
Calculated SHA-1: 378aed8b08e92e45d111fd51173cb6ac50edc2a2
ESET_targeting-Central-and-EasternEurope(07-01-2016).pdf
Reported SHA-1:   8d9af4bb8b4bafcb9e58ab21e1419abd2eed46b2
Calculated SHA-1: a0aff4e9e78fe99a358d520a4091328c8271d353
JPCERT_AsruexShortcutFiles(06-30-2016).pdf
Reported SHA-1:   0ddd9b23aaa773615e7d6392969d40b332e0c85f
Calculated SHA-1: 9b9fbcd9da3874154fa406f82d19c76272d153d4
Proofpoint_NetTraveler-TargetsRussianEuropean(07-07-2016).pdf
Reported SHA-1:   d647ecd9a694447bc8ee9096f425ba29d93f7fb7
Calculated SHA-1: 6b4fbf8d178569a1c6afdd0c4812ce051374ffac
Kaspersky_DroppingElephant(07-08-2016).pdf
Reported SHA-1:   e0606a9e6a785d942b50d281d87550dc03d3666e
Calculated SHA-1: 6e323df8f1cf1fe33edfffe91f5ac88b6693091b
```

Is box watermarking the downloads to make them each unique?  Are there instructions on how to download these files "correctly" so hashes match?  If the hashes are never going to match, you might not want to include them at all in the data files.

**Comment by beast-fighter** [comment]
I tested 4 of the ones you pointed out and am unable to replicate your issue:

PaloAlto_PrinceofPersiaGameOver(06-28-2016).pdf
Reported: 3f92bfbfdb0fee7eda8613fc3a6ff515ffceb972
From the box version: 3f92bfbfdb0fee7eda8613fc3a6ff515ffceb972
===
Bitdefender_Pacifier-APT(7-1-2016).pdf
Reported: 6289dff2cbd2750c76517007989483922179fa40
From the box version: 6289dff2cbd2750c76517007989483922179fa40
===
Cymmetria_Unveiling-Patchwork(Jul-7-16).pdf
Reported: 955ddb4453827e2c1664f2924e75b21fb0c0496d
From the box version: 955ddb4453827e2c1664f2924e75b21fb0c0496d
===
Kaspersky_DroppingElephant(07-08-2016).pdf
Reported: e0606a9e6a785d942b50d281d87550dc03d3666e
From the box version: e0606a9e6a785d942b50d281d87550dc03d3666e

However, if you are attempting to script the download of all the share URLs (using wget, requests, etc), this will more than likely not work as they require app interaction to initiate the download.

The hashes you are more than likely getting are the response content html not the PDF.

Cheers,

**Comment by aggiebill** [comment]
You are correct, I should have looked at what was being downloaded more closely.

```
$ head Kaspersky_DroppingElephant\(07-08-2016\).pdf 

<!DOCTYPE html>
<html lang="en-US" data-resin-client="web" data-resin-application="files" data-resin-page="sharedfilepreview">
<head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
```

I will have to figure out how to use the Box SDK to get the actual content.

Thanks!
