### ISSUE TITLE
Add Unit42 report on Wekby DNS request C2

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#4]
Release date: (05/24/2016)

Vendor: Palo Alto

Link: http://researchcenter.paloaltonetworks.com/2016/05/unit42-new-wekby-attacks-use-dns-requests-as-command-and-control-mechanism/

PDF:

Group: Wekby

Other:

**Comment by kbandla** [comment]
[Wekby.pdf](https://github.com/aptnotes/data/files/282886/Wekby.pdf)

**Comment by beast-fighter** [comment]
added in 79de337
