### ISSUE TITLE
Double listed report

### ISSUE THREAD

**Issue by aggiebill** [aptnotes/data#44]
The note was published in 2013, but is listed twice in both the CSV and JSON files.

NYTimes_Attackers_Evolve_Quickly,Survival Of The Fittest: New York Times Attackers Evolve Quickly,FireEye,https://app.box.com/s/fkg2mxeqpb2ivx9neyz6bseopy1dfg5p,5f17e7b886d2388ffc134157dd1b66aa65372b59,08/12/2013,2013
NYTimes_Attackers_Evolve_Quickly,Survival Of The Fittest: New York Times Attackers Evolve Quickly,FireEye,https://app.box.com/s/fkg2mxeqpb2ivx9neyz6bseopy1dfg5p,5f17e7b886d2388ffc134157dd1b66aa65372b59,08/12/2014,2014

**Comment by beast-fighter** [comment]
Thanks for reporting, fixed in fd944ca
