### ISSUE TITLE
Hunting Libyan Scorpions - Cyberkov Security

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#45]
Release date: (09/18/2016)

Vendor: Cyberkov Security

Link: https://cyberkov.com/hunting-libyan-scorpions/

PDF: https://cyberkov.com/wp-content/uploads/2016/09/Hunting-Libyan-Scorpions-EN.pdf

Group: Libyan Scorpions

Other:
https://cyberkov.com/wp-content/uploads/2016/09/Libyan-Scorpions-IoCs.xlsx

**Comment by beast-fighter** [comment]
added to box

**Comment by kbandla** [comment]
Added in bb8e7b35bd561711f1a1bf25d049e494e994049e
