### ISSUE TITLE
Sofacy’s ‘Komplex’ OS X Trojan

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#46]
Release date: (09/26/2016)

Vendor: PAN (Unit 42)

Link: http://researchcenter.paloaltonetworks.com/2016/09/unit42-sofacys-komplex-os-x-trojan/

PDF:

Group: Sofacy (APT28)

Other:

**Comment by kbandla** [comment]
`PaloAlto_Sofacys_Komplex_OSXTrojan(09-26-2016).pdf` added to box
`fb15f1de386ed3102956ff732b50c35ef56548b5`
