### ISSUE TITLE
The Ghost Dragon - Cylance

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#48]
Please fill out the information below

Release date: (04/22/2016)

Vendor: Cylance

Link: https://blog.cylance.com/the-ghost-dragon

PDF: Attached

Group: N/A

Other:  Gh0st RAT

[The Ghost Dragon - Cylance.pdf](https://github.com/aptnotes/data/files/504902/The.Ghost.Dragon.-.Cylance.pdf)

**Comment by beast-fighter** [comment]
added to box
