### ISSUE TITLE
[Kaspersky] Wave your false flags!

### ISSUE THREAD

**Issue by kbandla** [aptnotes/data#51]
Please fill out the information below
> Wave your false flags! Deception tactics muddying attribution in targeted attacks

Release date: (10/05/2016)

Vendor: Kaspersky

Link: 

PDF:https://securelist.com/files/2016/10/Bartholomew-GuerreroSaade-VB2016.pdf

Group:

Other:

Interesting paper. Not sure how/where to add this, but will figure out.

**Comment by beast-fighter** [comment]
Added to box
