### ISSUE TITLE
On the StrongPity Waterhole Attacks Targeting Italian and Belgian Encryption Users

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#52]
Please fill out the information below

Release date: (10/03/2016)

Vendor: Kaspesky

Link: https://securelist.com/blog/research/76147/on-the-strongpity-waterhole-attacks-targeting-italian-and-belgian-encryption-users/

PDF: N/A

Group: StrongPity

Other:

**Comment by kbandla** [comment]
`Kaspersky_StrongPity-Waterhole-Targeting-Italian-Belgian-Encryption-Users(10-03-2016)` added to box
`f4c3883bdb12af3225b3b57f2d8352cb37586312`
