### ISSUE TITLE
En Route with Sednit Part 1: Approaching the Target

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#53]
Please fill out the information below

Release date: (10/20/2016)

Vendor: ESET

Link: http://www.welivesecurity.com/wp-content/uploads/2016/10/eset-sednit-part1.pdf

PDF: http://www.welivesecurity.com/wp-content/uploads/2016/10/eset-sednit-part1.pdf

Group: APT28, SEDNIT, Sofacy, Fancy Bear

Other:

**Comment by kbandla** [comment]
`eset-sednit-part1(10-20-2016)` added to box
`aa59479dccb863926ace7d5a6d87e356eb9dad4a`
