### ISSUE TITLE
En Route With Sednit Part 2: Observing the Comings and Goings

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#55]
Please fill out the information below

Release date: (10/25/2016)

Vendor: ESET

Link: http://www.welivesecurity.com/2016/10/25/lifting-lid-sednit-closer-look-software-uses/
PDF: http://www.welivesecurity.com/wp-content/uploads/2016/10/eset-sednit-part-2.pdf

Group: Sednit/APT28/Fancy Bear/Sofacy

Other:

**Comment by kbandla** [comment]
`eset-sednit-part-2(10-25-2016)` added to box
`6f1dfb7fc2367f5787b076deb44f37704a682caa`
