### ISSUE TITLE
Know Your Enemies 2.0: A Primer on Advanced Persistent Threat Groups

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#56]
Please fill out the information below

Release date: (02/08/2016)

Vendor: ICIT
[ICIT-Brief-Know-Your-Enemies-2.0.pdf](https://github.com/aptnotes/data/files/551828/ICIT-Brief-Know-Your-Enemies-2.0.pdf)

Link: http://icitech.org/know-your-enemies-2-0/ (PDF is no longer on site)

PDF: Attached

Group: Multiple

Other:

**Comment by kbandla** [comment]
`ICIT-Brief-Know-Your-Enemies-2.0(02-08-2016).pdf` added to box
`6cc38d03649b53205ea47fad7672a39480be93ab`
