### ISSUE TITLE
Houdini’s Magic Reappearance

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#57]
Please fill out the information below

Release date: (10/25/2016)

Vendor: Palo Alto Networks

Link: http://researchcenter.paloaltonetworks.com/2016/10/unit42-houdinis-magic-reappearance/

PDF: Attached

Group: N/a

Other: Houdini, H-Worm
[Houdini’s Magic Reappearance - Palo Alto Networks Blog.pdf](https://github.com/aptnotes/data/files/555500/Houdini.s.Magic.Reappearance.-.Palo.Alto.Networks.Blog.pdf)

**Comment by kbandla** [comment]
`PaloAlto_Houdinis-Magic-Reappearance(10-25-2016).pdf` added to box
`242a98ec10de9c8044a355cbac843987d891b264`
