### ISSUE TITLE
Threat Group-4127 Targets Hillary Clinton Presidential Campaign

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#58]
Please fill out the information below

Release date: (06/16/2016)

Vendor: Dell Secureworks

Link:  https://www.secureworks.com/research/threat-group-4127-targets-hillary-clinton-presidential-campaign

PDF: Atatched

Group: APT28, TG-4127, Sofacy, Tsar Team
[Threat Group-4127 Targets Hillary Clinton Presidential Campaign - Dell Secureworks.pdf](https://github.com/aptnotes/data/files/555550/Threat.Group-4127.Targets.Hillary.Clinton.Presidential.Campaign.-.Dell.Secureworks.pdf)

Other:

**Comment by kbandla** [comment]
`DellSecureworks_ThreatGroup-4127-Targets-Clinton-Campaign(06-16-2016).pdf` added to box
`9f1be920242bc0b1cca697c0b5034c24a9e9c0a9`
