### ISSUE TITLE
Moonlight – Targeted attacks in the Middle East

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#59]
Please fill out the information below

Release date: (10/26/2016)

Vendor: Vectra Networks

Link: http://blog.vectranetworks.com/blog/moonlight-middle-east-targeted-attacks

PDF: Attached
[Moonlight – Targeted attacks in the Middle East - Vectra Networks.pdf](https://github.com/aptnotes/data/files/555580/Moonlight.Targeted.attacks.in.the.Middle.East.-.Vectra.Networks.pdf)

Group:

Other:

**Comment by kbandla** [comment]
`VectraNetworks_Moonlight_Targeted_attacks_Middle_East(10-26-2016).pdf` added to box
`2ad4ca5919036c23d608723cebd6eca8cd6d7240`
