### ISSUE TITLE
BLACKGEAR Espionage Campaign Evolves, Adds Japan To Target List

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#60]
Please fill out the information below

Release date: (10/27/2016)

Vendor: Trend Micro

Link:  http://blog.trendmicro.com/trendlabs-security-intelligence/blackgear-espionage-campaign-evolves-adds-japan-target-list/

PDF: Attached
[BLACKGEAR Espionage Campaign Evolves - Trend Micro.pdf](https://github.com/aptnotes/data/files/555643/BLACKGEAR.Espionage.Campaign.Evolves.-.Trend.Micro.pdf)

Group:
BLACKGEAR 
Other:

**Comment by kbandla** [comment]
`TrendMicro_BLACKGEAR-Espionage-Campaign(10-27-2016)` added to box
`bd52c0809e379a7dabdb35fcbb07d077f10a6edc`
