### ISSUE TITLE
Booz Allen: When The Lights Went Out: Ukraine Cybersecurity Threat Briefing

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#62]
Please fill out the information below

Release date: (11/3/2016)

Vendor: Booz Allen

Link: 

PDF: http://www.boozallen.com/content/dam/boozallen/documents/2016/09/ukraine-report-when-the-lights-went-out.pdf

Group:

Other:

**Comment by kbandla** [comment]
`BoozAllen_ukraine-report-when-the-lights-went-out(11-3-2016)` added to box
`6a6ad533b71fd64fc9dd4948e920a0992f637302`
