### ISSUE TITLE
The Dukes: 7 Years Of Russian Cyber-Espionage

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#63]
Please fill out the information below

Release date: (09/17/2015)

Vendor: F-Secure

Link:  https://labsblog.f-secure.com/2015/09/17/the-dukes-7-years-of-russian-cyber-espionage/

PDF:
[dukes_whitepaper - f-secure.pdf](https://github.com/aptnotes/data/files/585592/dukes_whitepaper.-.f-secure.pdf)

Group: 

Other: It's on the JSON but it's missing from the old repo. If it's not a problem then please ignore

**Comment by beast-fighter** [comment]
already exists:
F-Secure_TheDukes_whitepaper(9-17-15)
THE DUKES: 7 years of Russian cyberespionage
F-Secure
https://app.box.com/s/ipsg0t3krs811gesknvxrdsqhsknbydj
c02195e501548fc9b8e2e13673a7e12e1af9e207
09/17/2015 | 2015

**Comment by beast-fighter** [comment]
We are no longer updating the old repo
