### ISSUE TITLE
PowerDuke: Widespread Post-Election Spear Phishing Campaigns Targeting Think Tanks and NGOs

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#64]
Please fill out the information below

Release date: (11/09/2016)

Vendor: Volexity

Link:  https://www.volexity.com/blog/2016/11/09/powerduke-post-election-spear-phishing-campaigns-targeting-think-tanks-and-ngos/

PDF: 
[PowerDuke_ Widespread Post-Election Spear Phishing Campaigns Targeting Think Tanks and NGOs  - Volexity Blog.pdf](https://github.com/aptnotes/data/files/585593/PowerDuke_.Widespread.Post-Election.Spear.Phishing.Campaigns.Targeting.Think.Tanks.and.NGOs.-.Volexity.Blog.pdf)

Group:
APT29, Cozy Bear, Cozy Duke

Other:

**Comment by beast-fighter** [comment]
Added to Box:

https://app.box.com/s/wd73vlkdiry8hibkbqvmtsn0bhmzkhgk
SHA-1: 8b12bd8ad775ede8ccfffdbffe268dbf90a7731c
