### ISSUE TITLE
New Carbanak / Anunak Attack Methodology

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#65]
Please fill out the information below

Release date: (11/14/2016)

Vendor: Trustwave

Link: https://www.trustwave.com/Resources/SpiderLabs-Blog/New-Carbanak-/-Anunak-Attack-Methodology/

PDF:
[New Carbanak - Trustwave.pdf](https://github.com/aptnotes/data/files/591822/New.Carbanak.-.Trustwave.pdf)

Group:

Other:

**Comment by beast-fighter** [comment]
Added to box:
https://app.box.com/s/cbclbgiu54ihivxe7bvblwsv1e8jq44h
SHA-1: 21b1a684eb3ea41700740c13119707668a706c54
