### ISSUE TITLE
Carbanak Oracle Breach - Visa

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#66]
Please fill out the information below

Release date: (08/08/2016)

Vendor: Visa

Link: https://usa.visa.com/content/dam/VCOM/global/partner-with-us/documents/visa-pfd-micros-alert.pdf

PDF: https://usa.visa.com/content/dam/VCOM/global/partner-with-us/documents/visa-pfd-micros-alert.pdf

Group:

Other:

**Comment by beast-fighter** [comment]
Added to box:
https://app.box.com/s/4sfhcqaaxwui1dbvd13254wm5wfy9bmk
SHA-1: 8dcd6158f82898310af73d9fbeae8e626dbfdb7b
