### ISSUE TITLE
Carbanak Oracle Breach - Krebs on Security

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#67]
Please fill out the information below

Release date: (08/13/2016)

Vendor: Krebs on Security 

Link: https://krebsonsecurity.com/2016/08/visa-alert-and-update-on-the-oracle-breach/

PDF:
[Carbanak - Oracle breach - Kres on Security.pdf](https://github.com/aptnotes/data/files/591843/Carbanak.-.Oracle.breach.-.Kres.on.Security.pdf)

Group:

Other:

**Comment by threatminer** [comment]
I know this isn't an intel report but the article and the indicators are useful contextual info for intel analysts. It's up to the analyst to determine whether to trust what Krebs says.

**Comment by kbandla** [comment]
`BrianKrebs_Carbanak-Oracle-breach(08-13-2016).pdf` added to box `af70e2e4750a95aa3748fc15e3c1fb92f1b47e29`
