### ISSUE TITLE
Carbanak is packing new guns - ESET

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#68]
Please fill out the information below

Release date: (09/08/2015)

Vendor: ESET

Link: http://www.welivesecurity.com/2015/09/08/carbanak-gang-is-back-and-packing-new-guns/

PDF: 
[Carbanak gang is back and packing new guns - ESET.pdf](https://github.com/aptnotes/data/files/591846/Carbanak.gang.is.back.and.packing.new.guns.-.ESET.pdf)

Group:

Other:

**Comment by beast-fighter** [comment]
Added to box:
https://app.box.com/s/h1dn7d6ptcpwjbcfj468fy5201ev4bbz
SHA-1: 167f87b0bd4d0dcb9c57945189b4c019bdff9f3c
