### ISSUE TITLE
BITTER: A TARGETED ATTACK AGAINST PAKISTAN

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#69]
Please fill out the information below

Release date: (10/26/2016)

Vendor: Forcepoint

Link: https://blogs.forcepoint.com/security-labs/bitter-targeted-attack-against-pakistan

PDF: 
[BITTER - A TARGETED ATTACK AGAINST PAKISTAN - Forcepoint.pdf](https://github.com/aptnotes/data/files/603385/BITTER.-.A.TARGETED.ATTACK.AGAINST.PAKISTAN.-.Forcepoint.pdf)

Group:

Other:

**Comment by beast-fighter** [comment]
Added to box:
https://app.box.com/s/iegu4jz7v3q0vcvgrkzrnq3w28q3pyne
SHA-1: 22c73201d7e68dd0575e49942c8548c30b8c81a1
