### ISSUE TITLE
Add Citizen Lab Stealth Falcon Report

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#7]
Release date: (05/29/2016)

Vendor: Citizen Lab

Link: https://citizenlab.org/2016/05/stealth-falcon/

PDF: N/A

Group: Stealth Falcon

Other:

**Comment by kbandla** [comment]
[CitizenLab-Stealth_Falcon.pdf](https://github.com/aptnotes/data/files/293311/CitizenLab-Stealth_Falcon.pdf)

**Comment by kbandla** [comment]
Added in bb038e5861a0dc8b0b614cfd85f9a6ce05dce307
