### ISSUE TITLE
It’s Parliamentary: KeyBoy and the targeting of the Tibetan Community

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#70]
Please fill out the information below

Release date: (11/17/2016)

Vendor: Citizen Lab

Link: https://citizenlab.org/2016/11/parliament-keyboy/

PDF:
[It’s Parliamentary_ KeyBoy and the targeting of the Tibetan Community - The Citizen Lab.pdf](https://github.com/aptnotes/data/files/606236/It.s.Parliamentary_.KeyBoy.and.the.targeting.of.the.Tibetan.Community.-.The.Citizen.Lab.pdf)
Group:

Other:

**Comment by beast-fighter** [comment]
Added to box:
https://app.box.com/s/q7rywbgt6s5c380vvjpk643ppcdtdl8v
SHA-1: 59d42f8708403ea274fed447916543f26f56e51c
