### ISSUE TITLE
APT GROUP SENDS SPEAR PHISHING EMAILS TO INDIAN GOVERNMENT OFFICIALS

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#71]
Please fill out the information below

Release date: (06/03/2016)

Vendor: FireEye

Link: https://www.fireeye.com/blog/threat-research/2016/06/apt_group_sends_spea.html

PDF:
[APT Group Sends Spear Phishing Emails to Indian Government Officials « Threat Research Blog _ FireEye Inc.pdf](https://github.com/aptnotes/data/files/621811/APT.Group.Sends.Spear.Phishing.Emails.to.Indian.Government.Officials.Threat.Research.Blog._.FireEye.Inc.pdf)

Group:

Other:

**Comment by beast-fighter** [comment]
Added to box:
https://app.box.com/s/5hn3fparz8n2bmjpwzvxbds7gcnb7kum
SHA-1: 77d6090943f90b3c87f603e28b99f8a9e3e965d5

**Comment by kbandla** [comment]
Just realized this was already added before. Going to undo this commit
