### ISSUE TITLE
MALWARE ACTORS USING NIC CYBER SECURITY THEMED SPEAR PHISHING TO TARGET INDIAN GOVERNMENT ORGANIZATIONS

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#72]
Please fill out the information below

Release date: (11/30/2016)

Vendor: Cysinfo

Link: https://cysinfo.com/malware-actors-using-nic-cyber-security-themed-spear-phishing-target-indian-government-organizations/

PDF:
[Malware Actors Using NIC Cyber Security Themed Spear Phishing to Target Indian Government Organizations - Cysinfo.pdf](https://github.com/aptnotes/data/files/621817/Malware.Actors.Using.NIC.Cyber.Security.Themed.Spear.Phishing.to.Target.Indian.Government.Organizations.-.Cysinfo.pdf)

Group:

Other:

**Comment by beast-fighter** [comment]
Added to Box:
https://app.box.com/s/zsm16yh2sffqr9caehmifmvw2jrrwiga
SHA-1: 5a301a8947e72a5c4619adf4e7b30dd8bc80a400
