### ISSUE TITLE
Let It Ride: The Sofacy Group’s DealersChoice Attacks Continue

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#74]
Release date: (12/15/2016)

Vendor: Palo Alto (Unit42)

Link: http://researchcenter.paloaltonetworks.com/2016/12/unit42-let-ride-sofacy-groups-dealerschoice-attacks-continue/

PDF:

Group: Sofacy

Other:

**Comment by threatminer** [comment]
[The Sofacy Group’s DealersChoice Attacks Continue - Palo Alto.pdf](https://github.com/aptnotes/data/files/678711/The.Sofacy.Group.s.DealersChoice.Attacks.Continue.-.Palo.Alto.pdf)
