### ISSUE TITLE
The Luckycat Hackers

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#75]
Please fill out the information below

Release date: (04/03/2012)

Vendor: Symantec

Link: http://www.symantec.com/content/en/us/enterprise/media/security_response/whitepapers/the_luckycat_hackers.pdf

PDF:
[the_luckycat_hackers - Symantec.pdf](https://github.com/aptnotes/data/files/678619/the_luckycat_hackers.-.Symantec.pdf)

Group:

Other:

**Comment by kbandla** [comment]
`Symantec_The-luckycat-hackers(04-03-2012).pdf` added to box `3392452b5245a2e5b7299367f5588c75d44cca25`
https://app.box.com/s/oiblu3lk6fsqnjqv6bx4ygkv7e14tcb8
