### ISSUE TITLE
GRIZZLY STEPPE – Russian Malicious Cyber Activity

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#76]
Please fill out the information below

Release date: (12/29/2016)

Vendor: FBI

Link:  https://www.us-cert.gov/sites/default/files/publications/JAR_16-20296.pdf

PDF:
[JAR_16-20296.pdf](https://github.com/aptnotes/data/files/678667/JAR_16-20296.pdf)

Group:

Other:

**Comment by kbandla** [comment]
`USCERT_GRIZZLY STEPPE(12-29-2016).pdf` added to box `6c167fbcf1f24da37ded712e81f46cb82acdc3c0`
