### ISSUE TITLE
Danger Close: Fancy Bear Tracking of Ukrainian Field Artillery Units

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#77]
Please fill out the information below

Release date: (12/22/2016)

Vendor: Crowdstrike

Link: https://www.crowdstrike.com/blog/danger-close-fancy-bear-tracking-ukrainian-field-artillery-units/

PDF:
[FancyBearTracksUkrainianArtillery Blog  - Crowdstrike.pdf](https://github.com/aptnotes/data/files/678700/FancyBearTracksUkrainianArtillery.Blog.-.Crowdstrike.pdf)
[FancyBearTracksUkrainianArtillery  - Crowdstrike.pdf](https://github.com/aptnotes/data/files/678699/FancyBearTracksUkrainianArtillery.-.Crowdstrike.pdf)

Group:

Other:

**Comment by kbandla** [comment]
`Crowdstrike_FancyBearTracksUkrainianArtillery(12-22-2016).pdf` added to box `31fff8f0aab57b8edf24a77d7be9c10375ace768`
https://app.box.com/s/8lj785rl608lsmf80bwvtuxb7b9mscxy
