### ISSUE TITLE
RSA Incident Response: Emerging Threat Profile - Shell_Crew

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#78]
Please fill out the information below

Release date: (01/02/2014)

Vendor: RSA

Link: 
https://www.emc.com/collateral/white-papers/h12756-wp-shell-crew.pdf

PDF:
[RSA Incident Response Emerging Threat Profile_ Shell Crew.pdf](https://github.com/aptnotes/data/files/679025/RSA.Incident.Response.Emerging.Threat.Profile_.Shell.Crew.pdf)

Group:

Other:

**Comment by kbandla** [comment]
This report already exists. The shasum matches as well: 
```
h12756-wp-shell-crew
Emerging Threat Profile Shell_Crew RSA
https://app.box.com/s/xqldk5renv5ecihr7wyyazplrnezknmx
ec6771a81e830f50c2d54b26dc0f6a642439ee09
01/21/2014
2014
```
