### ISSUE TITLE
Snake In The Grass: Python-based Malware Used For Targeted Attacks

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#79]
Please fill out the information below

Release date: (06/10/2014)

Vendor: Blue Coat Labs

Link: https://www.bluecoat.com/security-blog/2014-06-10/snake-grass-python-based-malware-used-targeted-attacks

PDF:
[Snake In The Grass - Python-based Malware Used For Targeted Attacks - BLUE COAT LABS.pdf](https://github.com/aptnotes/data/files/679036/Snake.In.The.Grass.-.Python-based.Malware.Used.For.Targeted.Attacks.-.BLUE.COAT.LABS.pdf)
Group:

Other:

**Comment by kbandla** [comment]
```
{'Date': '06/10/2014',
 'Filename': u'Bluecoat_SnakeInTheGrass-Python-Malware-Targeted(06-10-2014).pdf',
 'Pdf': u'https://app.box.com/s/4n263mzodo4mb7jz1w3deidg9xuu2teh',
 'SHA-1': '7132fa8920490fd6f33a464f7018fbd0baffb43b',
 'Source': 'Bluecoat',
 'Title': 'Snake In The Grass: Python-based Malware Used For Targeted Attacks',
 'Year': '2014'}
```
