### ISSUE TITLE
The "Digital Plagiarist" Campaign: TelePorting the Carbanak Crew to a New Dimension

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#80]
Release date: (1/1/2017)

Vendor: tr1adx

Link: https://www.tr1adx.net/intel/TIB-00002.html

PDF: N/A

Group: TelePort Crew (aka: Carbanak/Anunak)

Other:

**Comment by beast-fighter** [comment]
https://www.tr1adx.net/intel/public/TIB-00002_IOC_Domain.txt (Domain IOCs)
https://www.tr1adx.net/intel/public/TIB-00002_IOC_IP.txt (IP IOCs)
https://www.tr1adx.net/intel/public/TIB-00002_IOC_FileHash.txt (Filehash IOCs)

**Comment by kbandla** [comment]
```
{'Date': '01/01/2017',
 'Filename': u'tr1adx_Digital-Plagarist-Carbanak(01-01-2017).pdf',
 'Pdf': u'https://app.box.com/s/7pr8b7cy9liv1bi88ha7frtzgrjycex3',
 'SHA-1': 'b7dc94c416b4e9c080448f76a9cfbdfd211c1a8c',
 'Source': 'tr1adx',
 'Title': 'The "Digital Plagiarist" Campaign: TelePorting the Carbanak Crew to a New Dimension',
 'Year': '2017'}
```
