### ISSUE TITLE
Threat Group-4127 Targets Google Accounts

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#81]
Please fill out the information below

Release date: (06/26/2016)

Vendor: Secureworks

Link: https://www.secureworks.com/research/threat-group-4127-targets-google-accounts

PDF:
[Threat Group-4127 Targets Google Accounts - Secureworks.pdf](https://github.com/aptnotes/data/files/687489/Threat.Group-4127.Targets.Google.Accounts.-.Secureworks.pdf)

Group:

Other:

**Comment by kbandla** [comment]
```
{'Date': '06/26/2016',
 'Filename': u'Secureworks_ThreatGroup-4127-Targets-Google-Accounts(06-26-2016).pdf',
 'Pdf': u'https://app.box.com/s/2y2p7im0bp3o5myvi5s9cxfchddn2zbd',
 'SHA-1': '4b340fd7ca63937db459345ebbf915a9dd5cfe01',
 'Source': 'Secureworks',
 'Title': 'Threat Group-4127 Targets Google Accounts',
 'Year': '2016'}
```
