### ISSUE TITLE
Foreign Cyber Threats to the United States

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#82]
Release date: (1/5/2017)

Vendor: United States Senate Committee on Armed Services

Link: http://www.armed-services.senate.gov/hearings/17-01-05-foreign-cyber-threats-to-the-united-states

PDF: http://www.armed-services.senate.gov/imo/media/doc/Clapper-Lettre-Rogers_01-05-16.pdf

Group: APT28/APT29/FancyBear

Other:

**Comment by beast-fighter** [comment]
Added to box:

SHA-1: a2c34f3b86cabbe9b99fb5456b763be432ac83c9
Box: https://app.box.com/s/vdwlyc9pcz8ycsbc8y39sjt47k9e904r

**Comment by kbandla** [comment]
```
{'Date': '01/05/2017',
 'Filename': u'UnitedStates_-Senate_Committee_-on_Armed_Services-Clapper-Lettre-Rogers(01-05-2017).pdf',
 'Pdf': u'https://app.box.com/s/a2yfu1q6j67gi6om5uum34if5cnztln2',
 'SHA-1': 'a2c34f3b86cabbe9b99fb5456b763be432ac83c9',
 'Source': 'US Senate Committee on Armed Services',
 'Title': 'Foreign Cyber Threats to the United States',
 'Year': '2017'}
```
