### ISSUE TITLE
Iranian Threat Agent OilRig Delivers Digitally Signed Malware, Impersonates University of Oxford

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#83]
Please fill out the information below

Release date: (01/05/2017)

Vendor: ClearSky

Link: http://www.clearskysec.com/oilrig/

PDF:
[Iranian Threat Agent OilRig Delivers Digitally Signed Malware, Impersonates University of Oxford _ ClearSky Cybersecurity.pdf](https://github.com/aptnotes/data/files/687527/Iranian.Threat.Agent.OilRig.Delivers.Digitally.Signed.Malware.Impersonates.University.of.Oxford._.ClearSky.Cybersecurity.pdf)

Group:

Other:

**Comment by kbandla** [comment]
```
{'Date': '01/05/2017',
 'Filename': u'Clearsky_Iranian-OilRig-Delivers-Signed-Oxford(01-05-2017).pdf',
 'Pdf': u'https://app.box.com/s/o3jg5us2c3lmeszk1m09hmenca0xnmgc',
 'SHA-1': '37b20be7b373b82bda3d72b17b21e2e41feba382',
 'Source': 'Clearsky',
 'Title': 'Iranian Threat Agent OilRig Delivers Digitally Signed Malware, Impersonates University of Oxford',
 'Year': '2017'}
```
