### ISSUE TITLE
MM CORE IN-MEMORY BACKDOOR RETURNS AS "BIGBOSS" AND "SILLYGOOSE"

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#85]
Please fill out the information below

Release date: (01/05/2017)

Vendor: Forcepoint

Link:  https://blogs.forcepoint.com/security-labs/mm-core-memory-backdoor-returns-bigboss-and-sillygoose

PDF: [MM CORE IN-MEMORY BACKDOOR RETURNS AS BIGBOSS AND SILLYGOOSE - Forcepoint.pdf](https://github.com/aptnotes/data/files/693110/MM.CORE.IN-MEMORY.BACKDOOR.RETURNS.AS.BIGBOSS.AND.SILLYGOOSE.-.Forcepoint.pdf)

Group:

Other:

**Comment by kbandla** [comment]
```
{'Date': '01/05/2017',
 'Filename': u'Forcepoint-MMCore-Fileless-Returns-BigBoss-SillyGoose(01-05-2017).pdf',
 'Pdf': u'https://app.box.com/s/4et31m42g0m8b1cj2ly2idlgruli1io6',
 'SHA-1': 'b62c407ee38c26946eff590f87a8ea186865a9a9',
 'Source': 'Forcepoint',
 'Title': 'Mm Core In-Memory Backdoor Returns As Bigboss And Sillygoose',
 'Year': '2017'}
```
