### ISSUE TITLE
APT28: AT THE CENTER OF THE STORM

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#87]
Please fill out the information below

Release date: (1/11/2017)

Vendor: FireEye

Link: https://www2.fireeye.com/WEB-2017-RPT-APT28.html

PDF: https://www2.fireeye.com/rs/848-DID-242/images/APT28-Center-of-Storm-2017.pdf

Group: APT28

Other:

Added to box:
Link: https://app.box.com/s/8987om4p7n48fm2n93k56kiwf8d08rgp
SHA-1: f5eb271671c7a2def034329d77843ac296266b0c

**Comment by kbandla** [comment]
```
{'Date': '01/11/2017',
 'Filename': u'FireEye_APT28-Center-of-Storm(01-11-2017).pdf',
 'Pdf': u'https://app.box.com/s/bh072li8eyb2daq5cnd88l1lms6ujhgf',
 'SHA-1': 'f5eb271671c7a2def034329d77843ac296266b0c',
 'Source': 'FireEye',
 'Title': 'At the Center of the Storm: Russia's APT28 Strategically Evolves its Cyber Operations',
 'Year': '2017'}
```
