### ISSUE TITLE
Red Line Drawn (FireEye) missing

### ISSUE THREAD

**Issue by mscox42** [aptnotes/data#89]
Please fill out the information below

Release Date: 6/20/2016

Vendor: FireEye

Link: https://www.fireeye.com/blog/threat-research/2016/06/red-line-drawn-china-espionage.html

PDF:https://www.fireeye.com/content/dam/fireeye-www/current-threats/pdfs/rpt-china-espionage.pdf

Group:multiple

Other:

**Comment by kbandla** [comment]
```
{'Date': '06/20/2016',
 'Filename': u'Fireeye-rpt-china-espionage(06-20-2016).pdf',
 'Pdf': u'https://app.box.com/s/jdk38pbsyaa19vb91uffmprn9oz4a2vr',
 'SHA-1': '4961a742b4c650d3fb84f9321de52911df176f1b',
 'Source': 'FireEye',
 'Title': 'Red Line Drawn: China Recalculates Its Use Of Cyber Espionage',
 'Year': '2016'}
```
