### ISSUE TITLE
Add Unit42 blog - Prince of Persia: Infy Malware Active In Decade of Targeted Attacks

### ISSUE THREAD

**Issue by beast-fighter** [aptnotes/data#9]
Release date: (05/02/2016)

Vendor: Palo Alto

Link: http://researchcenter.paloaltonetworks.com/2016/05/prince-of-persia-infy-malware-active-in-decade-of-targeted-attacks/

PDF:

Group:

Other:

**Comment by kbandla** [comment]
`PaloAlto_PrinceofPersiaInfyMalware(05-02-2016).pdf` added to box

**Comment by beast-fighter** [comment]
added in 93e9fa9
