### ISSUE TITLE
 AR-17-20045 Enhanced Analysis of GRIZZLY STEPPE Activity

### ISSUE THREAD

**Issue by bizarrechaos** [aptnotes/data#93]
Release date: 02/10/2017

Vendor: US-CERT

Link: https://www.us-cert.gov/ncas/current-activity/2017/02/10/Enhanced-Analysis-GRIZZLY-STEPPE

PDF: https://www.us-cert.gov/sites/default/files/publications/AR-17-20045_Enhanced_Analysis_of_GRIZZLY_STEPPE_Activity.pdf

Group: APT28, APT29

Other:

**Comment by kbandla** [comment]
```
{'Date': '02/10/2017',
 'Filename': u'US-CERT-AR-17-20045_Enhanced_Analysis_of_GRIZZLY_STEPPE_Activity(02-10-2017).pdf',
 'Pdf': u'https://app.box.com/s/zfhxta0cuh9yycoelyzaxgc03ir4b18u',
 'SHA-1': '7f8c3d1d34755bd52f850bad0bc2dc1db6783661',
 'Source': 'US-CERT',
 'Title': 'Enhanced Analysis of GRIZZLY STEPPE Activity',
 'Year': '2017'}
```
Thanks @bizarrechaos !
