### ISSUE TITLE
LAZARUS & WATERING-HOLE ATTACKS

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#96]
Please fill out the information below

Release date: (02/12/2017)

Vendor: BAE Systems

Link: https://baesystemsai.blogspot.co.uk/2017/02/lazarus-watering-hole-attacks.html

PDF:
[LAZARUS & WATERING-HOLE ATTACKS - BAE Systems.pdf](https://github.com/aptnotes/data/files/790919/LAZARUS.WATERING-HOLE.ATTACKS.-.BAE.Systems.pdf)

Group:

Other:

**Comment by kbandla** [comment]
```
{'Date': '02/12/2017',
 'Filename': u'BAESystems_Lazarus-Watering-hole-attacks(02-12-2017).pdf',
 'Pdf': u'https://app.box.com/s/7wh9z15na9c823vtwo8fhyu2qt6a57df',
 'SHA-1': 'fddefc914c62f4886d6ce9b889a3fbe8769fa886',
 'Source': 'BAE Systems',
 'Title': 'Lazarus & Watering-Hole Attacks',
 'Year': '2017'}
```

Thanks @threatminer !
