### ISSUE TITLE
LAZARUS’ FALSE FLAG MALWARE

### ISSUE THREAD

**Issue by threatminer** [aptnotes/data#97]
Please fill out the information below

Release date: (02/20/2017)

Vendor: BAE Systems

Link: http://baesystemsai.blogspot.co.uk/2017/02/lazarus-false-flag-malware.html

PDF:
[LAZARUS FALSE FLAG MALWARE - BAE Systems.pdf](https://github.com/aptnotes/data/files/790923/LAZARUS.FALSE.FLAG.MALWARE.-.BAE.Systems.pdf)

Group:

Other:

**Comment by kbandla** [comment]
```
{'Date': '02/20/2017',
 'Filename': u'BAESystems_Lazarus-FalseFlag-Malware(02-20-2017).pdf',
 'Pdf': u'https://app.box.com/s/t5f8jofli5p969wsc0lydfdzihbnto93',
 'SHA-1': '4068d909a958924e1d908f6adc21ea998d1eb891',
 'Source': 'BAE Systems',
 'Title': "Lazarus' False Flag Malware",
 'Year': '2017'}
```
